<?php

/**
 * @file
 * Provides hooks for the Debug Pause Module.
 */

/**
 * Implements hook_toolbar_alter() for injecting libraries.
 */
function debugpause_toolbar_alter(&$items) {
  $items['administration']['#attached']['library'][] = 'debugpause/toolbar.debug-pause';
}

/**
 * Implements hook_preprocess_HOOK() for inject attribute and conditionally render the menu item.
 */
function debugpause_preprocess_menu(&$variables) {
  $items = $variables['items'];
  foreach ($items as $key => &$item) {
    // Hide  link if the user is logged in.
    if ($item['title'] == 'Debug Pause' && !\Drupal::currentUser()->hasPermission('use debug pause')) {
      unset($variables['items'][$key]);
    }
    elseif ($item['title'] == 'Debug Pause' && \Drupal::currentUser()->hasPermission('use debug pause')) {
      // Attributes config value to the menu element and attributes ID.
      $item['attributes']['pausein'] = \Drupal::config('debugpause.settings')->get('pausein');
      $item['attributes']['id'] = 'debugpausebutton';
    }
  }
}
